# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/75B2-AA88";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # 配置BTRFS的压缩功能
    fileSystems."/" =
    { device = "/dev/disk/by-uuid/6ac89ad8-a5e6-4ca3-8505-856c27a28183";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/31f858cd-ca17-4221-95b0-651f75f2cfc5";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
