# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{  lib,  modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a667d568-f0a7-48d7-914a-962d77912df8";
      fsType = "xfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5ac20756-f595-4ac1-aa68-5eb0e94b03ad";
      fsType = "xfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F313-F3CF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # ✅ 显式声明 AMD CPU 微码更新（原为隐式 mkDefault 依赖 enableRedistributableFirmware）
  # 作用: 微码安全更新（当前版本 0xa201213 已生效）
  # 说明: Ryzen 5000 (Zen 3) 微码更新对性能影响 <1%，且本改动不改变实际行为
  #       仅将隐式生效的配置显式化，避免依赖 mkDefault 链
  # 官方选项: https://search.nixos.org/options?query=hardware.cpu.amd.updateMicrocode
  hardware.cpu.amd.updateMicrocode = true;
}
