# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D905-253B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # 配置BTRFS的压缩功能
    fileSystems."/" =
    { device = "/dev/disk/by-uuid/1418cb46-1d6c-4f9e-a9a3-925c71782521";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ec2a8628-f764-4371-98f2-220e1a2f8d0f";
      fsType = "btrfs";
      options = [ "compress=zstd" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
