# Matugen input template for keytop/colors.conf.
[colors]
surface=#131318
on_surface=#e4e1e9
primary=#bbc3ff
on_surface_variant=#c7c5d0
outline_variant=#46464f
tertiary=#e6bad7
error=#ffb4ab
primary_container=#3b4279
on_primary_container=#dfe0ff
secondary=#c4c5dd
