complete -c key -f -n '__fish_use_subcommand' -a shell -d 'start or inspect Clavis Quickshell'
complete -c key -f -n '__fish_use_subcommand' -a ipc -d 'route Clavis IPC'
complete -c key -f -n '__fish_use_subcommand' -a record -d 'record the screen'
complete -c key -f -n '__fish_use_subcommand' -a audio -d 'record audio to M4A'
complete -c key -f -n '__fish_use_subcommand' -a clipboard -d 'operate on clipboard history'
complete -c key -f -n '__fish_use_subcommand' -a doctor -d 'check runtime dependencies'
complete -c key -f -n '__fish_use_subcommand' -a version -d 'show version metadata'

complete -c key -f -n '__fish_seen_subcommand_from shell' -l daemon -s d -d 'start qs detached'
complete -c key -f -n '__fish_seen_subcommand_from shell' -l kill -s k -d 'stop the clavis configuration'
complete -c key -f -n '__fish_seen_subcommand_from shell' -l log -s l -d 'print the qs log'
complete -c key -f -n '__fish_seen_subcommand_from shell' -l show -s s -d 'show IPC methods'

complete -c key -f -n '__fish_seen_subcommand_from ipc' -a 'show list call'
complete -c key -f -n '__fish_seen_subcommand_from record' -a 'start status stop pause resume'
complete -c key -f -n '__fish_seen_subcommand_from audio' -a 'start status stop'
complete -c key -f -n '__fish_seen_subcommand_from clipboard' -a 'list inspect restore delete clear status'
complete -c key -f -n '__fish_seen_subcommand_from record audio' -l json -d 'write JSON'
complete -c key -f -n '__fish_seen_subcommand_from clipboard' -l format -a json -d 'JSON response'
